name: Generate Release Note

on:
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install
      - name: Generate Libraries
        run: npm run build
      - name: Generate release note
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          files: dist/*

