name: Generate Release Note

on:
  push:
    tags:
      - 'v*'
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Set the value
        id: step_one
        run: |
          echo ${{ github.ref_name }} | sed -e 's/^v//' | xargs -I {} echo "VERSION={}" >> "$GITHUB_ENV"
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install
      - name: Generate Libraries
        run: npm run build
      - name: Archive Release
        uses: thedoctor0/zip-release@0.7.6
        with:
          type: 'zip'
          filename: "simple-sample-${VERSION}.zip"
          directory: './dist/'
      - name: Generate release note
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          files: "dist/simple-sample-${VERSION}.zip"
